# Generated by Django 3.1.5 on 2021-01-15 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amznchecker', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Prices',
            new_name='Price',
        ),
        migrations.RenameModel(
            old_name='Products',
            new_name='Product',
        ),
    ]
